In [2]:
A = collect(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [3]:
B = collect(1:3:15)

5-element Array{Int64,1}:
  1
  4
  7
 10
 13

In [4]:
C = collect(1:0.5:5)

9-element Array{Float64,1}:
 1.0
 1.5
 2.0
 2.5
 3.0
 3.5
 4.0
 4.5
 5.0

In [7]:
typeof(ones(15))

Array{Float64,1}

In [8]:
typeof(zeros(15))

Array{Float64,1}

In [9]:
rand(1:100, 15)

15-element Array{Int64,1}:
 89
 51
  8
 88
 82
 85
 22
 87
 36
 18
 37
 36
 18
 23
 32

In [10]:
A = [1 2 3; 4 5 6]

2x3 Array{Int64,2}:
 1  2  3
 4  5  6

In [11]:
B = reshape(A, 3, 2)

3x2 Array{Int64,2}:
 1  5
 4  3
 2  6

In [12]:
C = transpose(B)

2x3 Array{Int64,2}:
 1  4  2
 5  3  6

In [13]:
A * B

2x2 Array{Int64,2}:
 15  29
 36  71

In [14]:
A / C

2x2 Array{Float64,2}:
 0.332273  0.27663 
 0.732909  0.710652

In [15]:
# A simple Markov chain - cat and mouse
I = eye(4)
P = [0 0 .5 0; 0 0 1 0; .25 .25 0 .25; 0 0 .5 0]
ep = [0 1 0 0] * inv(I - P) * [1, 1, 1, 1]
println("Expected lifetime for the mouse is $ep ticks")

Expected lifetime for the mouse is [4.5] ticks


In [16]:
A = b"HEX:\xefcc"

7-element Array{UInt8,1}:
 0x48
 0x45
 0x58
 0x3a
 0xef
 0x63
 0x63

In [17]:
B = b"\u2220 x \u2203 y"

11-element Array{UInt8,1}:
 0xe2
 0x88
 0xa0
 0x20
 0x78
 0x20
 0xe2
 0x88
 0x83
 0x20
 0x79

In [18]:
v"1"

v"1.0.0"

In [22]:
# A game simulation: Bulls and Cows
function bacs()
    bulls = cows = turn = 0
    A = []
    srand(int(time()))
    while length(unique(A)) < 4
        push!(A, rand('1': '9'))
    end
    bacs_number = unique(A)
    println("Bulls and Cows")
    while (bulls != 4)
        print("Guess? ")
        if eof(STDIN)
            s = "q"
        else
            s = chomp(readline(STDIN))
        end
        if (s == "q")
            print("My guess was ")
            [print(bacs_number[i]) for i = 1:4]
            return
        end
        guess = collect(s)
        if !(length(unique(guess)) == length(guess) == 4 &&
            all(isdigit, guess))
            print("\nEnter four distinct digits or q to quit: ")
            continue
        end
        bulls = sum(map(==, guess, bacs_number))
        cows = length(intersect(guess, bacs_number)) - bulls
        println("$bulls bulls and $cows cows!")
        turns += 1
    end
    println("You guessed my number in $turns turns.")
end

bacs (generic function with 1 method)