In [2]:
x = ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [3]:
y = [2, 4, 6]

3-element Array{Int32,1}:
 2
 4
 6

In [4]:
dot(x,y)

12.0

In [5]:
A = [1 2
3 4]

2x2 Array{Int32,2}:
 1  2
 3  4

In [6]:
typeof(A)

Array{Int32,2}

In [7]:
size(A)

(2,2)

In [8]:
A'

2x2 Array{Int32,2}:
 1  3
 2  4

In [9]:
A = [1.0 2.0; 2.0 1.0]

2x2 Array{Float64,2}:
 1.0  2.0
 2.0  1.0

In [10]:
evals, evecs = eig(A)

([-1.0,3.0],
2x2 Array{Float64,2}:
 -0.707107  0.707107
  0.707107  0.707107)

In [11]:
evals

2-element Array{Float64,1}:
 -1.0
  3.0

In [12]:
evecs

2x2 Array{Float64,2}:
 -0.707107  0.707107
  0.707107  0.707107